version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=galerie_oselo
      - DB_USER=galerie
      - DB_PASSWORD=password

  db:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=galerie_oselo
      - MYSQL_USER=galerie
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  db_data:

